import React from "react";

export default function InsightPanel({ aiSummary }) {
  return (
    <div className="card">
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 16 }}>
        <div style={{
          width: 32, height: 32,
          borderRadius: 8,
          background: "#1a2332",
          border: "1px solid #2d4a6e",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 16,
        }}>
          ◆
        </div>
        <div>
          <h3 style={{ fontSize: 15, fontWeight: 600 }}>AI postmortem</h3>
          <p style={{ fontSize: 12, color: "#8b949e" }}>Generated by Claude</p>
        </div>
      </div>

      <div style={{
        fontSize: 14,
        lineHeight: 1.75,
        color: "#c9d1d9",
        whiteSpace: "pre-wrap", // preserve paragraph breaks
      }}>
        {aiSummary || "No AI summary available."}
      </div>
    </div>
  );
}
